# Nome da Pipeline
name: TDW_Diogo_Guerra#2

# Quando a pipeline vai correr. Sempre que houver commit para qualquer branch (push) ou sempre que houver um pull request para qualquer branch
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

# Definição dos jobs que vão correr em paralelo
jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Limpar a cache (opcional)
      - name: Clear npm cache
        run: npm cache clean --force

      # Instalar todas as dependências
      - name: Install dependencies
        run: npm install
        working-directory: ./tdw-aleluia

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: install-dependencies  # Isto depende de install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Instalar Jest
      - name: Install Jest
        run: npm install jest
        working-directory: ./tdw-aleluia

      # Correr todos os testes automáticos
      - name: Run tests
        run: npm test -- -u 
        working-directory: ./tdw-aleluia

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./tdw-aleluia/coverage/coverage-final.json
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    needs: run-tests  # Isto depende da passagem dos testes
    if: success()  # Só vai se bem sucedido
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
