name: TDW_Diogo_Guerra#2

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install
        working-directory: ./tdw-aleluia

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Jest
        run: npm install jest
        working-directory: ./tdw-aleluia

      - name: Run tests
        run: npm test -- -u 
        working-directory: ./tdw-aleluia

      # Adicione uma etapa para listar arquivos e diretórios
      - name: List all files and directories
        run: ls -R
        working-directory: ./tdw-aleluia

      # Adicione uma etapa para listar arquivos de cobertura
      - name: List coverage files
        run: ls -l ./coverage
        working-directory: ./tdw-aleluia

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./tdw-aleluia/coverage/coverage-final.json
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    needs: run-tests
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'