name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use a versão LTS

      - name: Install dependencies
        run: npm install
        working-directory: ./tdw-aleluia

  run-lint:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Lint
        run: npx eslint .
        working-directory: ./tdw-aleluia

  run-tests:
    runs-on: ubuntu-latest
    needs: run-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jsdom
        run: npm install jest-environment-jsdom --save-dev
        working-directory: ./tdw-aleluia

      - name: Run tests
        run: npm test
        working-directory: ./tdw-aleluia

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./tdw-aleluia/coverage/coverage-final.json
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
